version: '3.3'

services:
  school-registration-db:
    container_name: school-registration-db
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: school-registration-system
      POSTGRES_USER: registrar
      POSTGRES_PASSWORD: registrar123
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - /tmp:/tmp:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
